apiVersion: v1
kind: Service
metadata:
  name: hdfs-datanode
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Values.Worker.Component }}"
spec:
  ports:
  - port: {{ .Values.Worker.ServicePort }}
    name: {{ .Values.Worker.PortName }}
    protocol: TCP
  clusterIP: None
  selector:
    component: {{ .Values.Worker.Component }}

---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: hdfs-datanode
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Values.Worker.Component }}"
spec:
  serviceName: "{{ .Values.Worker.Component }}"
  replicas: {{ default 1 .Values.Worker.Replicas }}
  template:
    metadata:
      labels:
        heritage: {{ .Release.Service | quote }}
        release: {{ .Release.Name | quote }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        component: "{{ .Values.Worker.Component }}"
    spec:
      containers:
        - name: hdfs-datanode
          image: {{ .Values.Worker.Image }}:{{ .Values.Worker.ImageTag }}
          env:
          - name: CORE_CONF_fs_defaultFS
            value: hdfs://hdfs-namenode-0.hdfs-namenode.default.svc.cluster.local:8020
          - name: HADOOP_DATANODE_MEMORY
            value: {{ default "1g" .Values.Worker.ExecutorMemory | quote }}
          ports:
          - containerPort: {{ .Values.Worker.ServicePort }}
            name: {{ .Values.Worker.PortName }}
      restartPolicy: Always

