apiVersion: v1
kind: Service
metadata:
  name: hdfs-namenode
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Release.Name }}-{{ .Values.Master.Component }}"
spec:
  ports:
    - port: {{ .Values.Master.ServicePort }}
      name: {{ .Values.Master.PortName }}
  selector:
   component: "{{ .Release.Name }}-{{ .Values.Master.Component }}"


---

apiVersion: v1
kind: Service
metadata:
  name: hdfs-webui
  labels:
    heritage: {{ .Release.Service | quote }} 
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Release.Name }}-{{ .Values.Master.Component }}"
spec:
  ports:
  - port: {{ .Values.WebUi.ServicePort }}
  selector:
    component: "{{ .Release.Name }}-{{ .Values.Master.Component }}"
  type: "LoadBalancer"
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: hdfs-namenode
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Release.Name }}-{{ .Values.Master.Component }}"
spec:
  serviceName: "{{ .Values.Master.Component }}"
  replicas: {{ default 1 .Values.Master.Replicas }}
  template:
    metadata:
      labels:
        heritage: {{ .Release.Service | quote }} 
        release: {{ .Release.Name | quote }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        component: "{{ .Release.Name }}-{{ .Values.Master.Component }}"  
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: {{ .Values.Master.Component }}
          image: {{ .Values.Master.Image }}
          env:
          - name: CLUSTER_NAME
            value: hdfs-aia  
          ports:
          - containerPort: {{ .Values.Master.ContainerPort }}
            name: {{ .Values.Master.PortName }}
      restartPolicy: Always     

