apiVersion: v1
kind: Service
metadata:
  name: hdfs-datanode
  labels:
    app: hdfs-datanode
spec:
  ports:
  - port: {{ .Values.Worker.ServicePort }}
    name: {{ .Values.Worker.PortName }}
  clusterIP: None
  selector:
    app: {{ .Values.Worker.Component }}

---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: hdfs-datanode
  labels:
    app: hdfs-datanode
spec:
  serviceName: "{{ .Values.Worker.Component }}"
  replicas: {{ default 1 .Values.Worker.Replicas }}
  template:
    metadata:
      labels:
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        app:{{ .Values.Worker.Component }}
    spec:
      containers:
        - name: {{ .Values.Worker.Component }}
          image: {{ .Values.Worker.Image }}
          env:
          - name: CORE_CONF_fs_defaultFS
            value: hdfs://hdfs-namenode-0.hdfs-namenode.default.svc.cluster.local:8020  
          ports:
          - containerPort: {{ .Values.Worker.ServicePort }}
            name: {{ .Values.Worker.PortName }}
      restartPolicy: Always

