apiVersion: v1
kind: Service
metadata:
  name: hdfs-namenode
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Values.Master.Component }}"
spec:
  ports:
    - port: {{ .Values.Master.ServicePort }}
      name: {{ .Values.Master.PortName }}
      protocol: TCP
  clusterIP: None
  selector:
   component: {{ .Values.Master.Component }}


---

apiVersion: v1
kind: Service
metadata:
  name: hdfs-webui
  labels:
    heritage: {{ .Release.Service | quote }} 
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Values.Master.Component }}"
spec:
  ports:
  - port: {{ .Values.WebUi.ServicePort }}
  selector:
    component: {{ .Values.Master.Component }}
  type: "LoadBalancer"
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: hdfs-namenode
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Values.Master.Component }}"
spec:
  serviceName: "{{ .Values.Master.Component }}"
  replicas: {{ default 1 .Values.Master.Replicas }}
  template:
    metadata:
      labels:
        heritage: {{ .Release.Service | quote }} 
        release: {{ .Release.Name | quote }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        component: "{{ .Values.Master.Component }}"  
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: hdfs-namenode
          image: {{ .Values.Master.Image }}:{{ .Values.Master.ImageTag }}
          env:
          - name: CLUSTER_NAME
            value: hdfs-k8s
          resources:
            requests:
              cpu: "{{ .Values.Master.Cpu }}"
              memory: "{{ .Values.Master.Memory }}"
          ports:
          - containerPort: {{ .Values.Master.ContainerPort }}
            name: {{ .Values.Master.PortName }}
      restartPolicy: Always     

